version: '3.9'

services:
  web:
    build: 
      context: ./.
      dockerfile: ang.Dockerfile
    container_name: myapp
    ports:
      - 80:80
    volumes:
      - ./myapp:/app
    depends_on:
      - api
  
  cache:
    image: redis:6.2-alpine
    container_name: cache 
    restart: unless-stopped
    ports:
      - 6379:6379

  api:
    build: 
      context: ./.
      dockerfile: node.Dockerfile
    container_name: nodealpine
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - cache
    environment:
      - REDIS_HOST=0.0.0.0
    volumes:
      - ./api/app.js:/usr/src/app/app.js
      - ./api/package.json:/usr/src/app/package.json